### ISSUE TITLE
please document the command line to build your software

### ISSUE THREAD

**Issue by bstarynk** [ProfessorShaban/risc-v-simulator#1]
(I am a Linux/Debian fan, actually Debian/Buster on x86-64)

What is the command line to build that software? `qtcreator` is installed, but I never used it

Thanks

<basile@starynkevitch.net>
http://starynkevitch.net/Basile/

**Comment by ProfessorShaban** [comment]
Hi Basile, thanks for your note. That’s a good suggestion and we will work on that,

Marwan

**Comment by ProfessorShaban** [comment]
We've now tested this on Debian. Please see README.md for command line build instructions
