### ISSUE TITLE
error: ‘class QFontMetrics’ 

### ISSUE THREAD

**Issue by fatalfeel** [ProfessorShaban/risc-v-simulator#2]
codeeditor.cpp: In member function ‘int CodeEditor::lineNumberAreaWidth()’:
codeeditor.cpp:166:36: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     int space = 13 + fontMetrics().horizontalAdvance(QLatin1Char('9')) * digits;

**Comment by ProfessorShaban** [comment]
It sounds like you're using a Qt version prior to 5.11. Please update the Qt version and let us know if you still get this error message
